//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatbracket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int Playerid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int Textoptin { get; set; }
        public string Handle { get; set; }
        public string Password { get; set; }
        public string Imagename { get; set; }
        public string Imagepath { get; set; }
        public System.DateTime Createddate { get; set; }
        public int Usertype { get; set; }
        public int Isactive { get; set; }
    }
}
